### ISSUE TITLE
LevelDB constructor crashes sometimes

### ISSUE THREAD

**Issue by iamnikv** [maxpert/LevelDBWinRT#1] opened 2018-12-07 12:49 UTC
I am creating a DB in one folder and sometimes I have to dispose that DB to create another one in it's place and this is when I get this error, sometimes:

_Unspecified error

IO error: Unable to move file, StackTrace:    at LevelDBWinRT.DB..ctor(Options options, String path)_

This happens right after I dispose the previous DB and around 15 lines of code later, when I try to create the new DB with the LevelDB constructor this exception is thrown.

**Comment by maxpert** [comment] 2018-12-11 15:16
Hey,

 So if you look at the code the destructor deletes the instance of LevelDB object and that should close all the required file handles. Error message points me to the fact that your DB is being used by something else (locked). Can you include the platform/device you are having trouble on? Also write small program to reproduce the issue.

**Comment by iamnikv** [comment] 2018-12-11 15:40
The isssue is reproduced on Windows 10 Pro, version 1803, OS build 17134.407, however it is not reproducible every time.

```csharp
_db?.Dispose();

string dbName = _userId;

if (dbName == "")
{
	dbName = LocalDbName;
}

StorageFolder dbFolder = await ApplicationData.Current.LocalFolder.CreateFolderAsync(DbFolderName, CreationCollisionOption.OpenIfExists);

var localDbPath = Path.Combine(dbFolder.Path, LocalDbName);
var userDbPath = Path.Combine(dbFolder.Path, dbName);

if (userDbPath != localDbPath && Directory.Exists(localDbPath) && !Directory.Exists(userDbPath))
{
	Directory.Move(localDbPath, userDbPath); // This is not executed in the case of the crash
}

foreach (var storageFolder in await dbFolder.GetFoldersAsync())
{
	if (storageFolder.Name != dbName)
	{
		await storageFolder.DeleteAsync(StorageDeleteOption.PermanentDelete);
	}
}

this._db = new LevelDb(new Options { CreateIfMissing = true }, userDbPath);
```
This is the code snippet where the crash happens. As you can see I first dispose the old database and after I delete the old database folder I try to create a new database and sometimes it seems like the old LOG file is locked...

**Comment by maxpert** [comment] 2018-12-11 17:32
Hmm so problem is probably not with LevelDB but the code itself. Because if you are deleting files and anything is being held up by LevelDB the `DeleteAsync` operation would have failed. One suggestion I might have is to move (rename) old DB folder before creating new database and then do the deletion later.

**Comment by iamnikv** [comment] 2018-12-12 12:09
Thank you for the advice. I was confused with this issue because I didn't understand why is there a locked file when first I awaited for the DeleteAsync to finish execution (doesn't this suppose to mean that the files were deleted and there is nothing left to be locked?) and second I created the new database in a completely different folder than the previous one (which was disposed and the folder, deleted). 

The other thing that I noticed and I did not understand was in db_impl.cc in the DBImpl constructor where SanitizeOptions() is called and in it this piece of code: 
```cplusplus
if (result.info_log == NULL) {
    // Open a log file in the same directory as the db
    src.env->CreateDir(dbname);  // In case it does not exist
    src.env->RenameFile(InfoLogFileName(dbname), OldInfoLogFileName(dbname));
    Status s = src.env->NewLogger(InfoLogFileName(dbname), &result.info_log);
    if (!s.ok()) {
      // No place suitable for logging
      result.info_log = NULL;
    }
  }
```

Why is a log file being renamed in a newly created folder?

**Comment by maxpert** [comment] 2018-12-16 15:18
That code directly comes from LevelDB codebase. So I won't comment on that, I can imagine it might be for recovery and replay crashed operation purposes. I will close the issue, it would be nice however that you can link back to your application (if it's already published). I am creating a list of applications using this code in production.

**Closed as completed by maxpert** 2018-12-16 15:18 UTC
